### PR TITLE
Add link library to adapt to the new version of SGX SDK and SSL 

### PR DESCRIPTION
**Pull request by tinoryj**
SDK: 2.15.100.3
SGX SSL: Linux 2.14 SGX SDK, OpenSSL 1.1.1k
Solved the problem that the original sgx_pthread link was incorrect

### CODE REVIEW

**Comment by xzhangxa** [comment]
Hello,

I see the new 2.15 SDK release on GitHub and 01.org and haven't tried it yet. What does this mean:
> SGX SSL: Linux 2.14 SGX SDK, OpenSSL 1.1.1k

SGX SDK 2.14 + OpenSSL 1.1.1k? Or typo 2.14 -> 2.15?

**Comment by tinoryj** [comment]
I mean that I have tested under this sgxssl version (https://github.com/intel/intel-sgx-ssl/releases/tag/lin_2.14_1.1.1k) with the latest SDK 2.15.100.3 (https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.15-release) .

**Comment by xzhangxa** [comment]
@tinoryj thanks for your contribution:)

The cmake file should be able to be used w/o the new `sgx-ssl`, so I added one more commit after yours to make it optional. #17 Please review whether it works.

**Comment by xzhangxa** [comment]
Close as the same commit is merged in #17

**Pull request closed without merging**
